---

- name: Copy our Jenkins init file.
  copy:
    src: jenkins-init
    dest: "{{ jenkins_init_script }}"
    owner: root
    group: root
    mode: 0755

#- name: Modify variables in init file
#  lineinfile:
#    dest: "{{ jenkins_init_file }}"
#    insertafter: '^{{ item.option }}='
#    regexp: '^{{ item.option}}=\"\${{ item.option }} '
#    line: '{{ item.option }}="${{ item.option }} {{ item.value }}"'
#    state: present
#  with_items:
#      "{{ jenkins_init_changes }}"
#  register: jenkins_init_prefix
#
#- name: Immediately restart Jenkins on init config changes.
#  command: "/bin/true"
#  when: jenkins_init_prefix.changed
#  notify: restart jenkins
#
- name: Set HTTP port in Jenkins config.
  lineinfile:
    backrefs: yes
    dest: "{{ jenkins_init_file }}"
    regexp: '^{{ jenkins_http_port_param }}='
    line: '{{ jenkins_http_port_param }}={{ jenkins_http_port }}'
  register: jenkins_http_config

- name: Create custom init scripts directory.
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Configure Jenkins default users.
  template:
    src: basic-security.groovy
    dest: /var/lib/jenkins/init.groovy.d/basic-security.groovy
  register: jenkins_users_config
  when: jenkins_install_package.changed

- name: Immediately restart Jenkins on http or user changes.
  command: "/bin/true"
  when: jenkins_users_config.changed or jenkins_http_config.changed
  notify: restart jenkins
